#!/usr/bin/env bash
# Check that Cobbler is able to build customized ISOs by the "cobbler buildiso" command

source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

# Preparations
cobbler distro add --name fake --arch x86_64 --kernel ${fake_kernel} --initrd ${fake_initramfs}

cobbler profile add --name fake --distro fake

cobbler system add --name testbed --profile fake

# Real test
cobbler buildiso --iso ${tmp}/autoinst.iso

# Check ISO exists
[ -f ${tmp}/autoinst.iso ]

# Check ISO is bootable - The tool "parti" must be available for this
# TODO
